apiVersion: v1
data:
  token: MC41Nzg0OTBhZC1lNTYzLTRjNjQtODM0Ni1iMmNmMDE4MGYyMTYuZDVUY2djTVhQN0tTdGVTTGk2Q2djaXdmN3JNVGFBOkYyNWdEYVI3eHVmN3NaSXNRSjVtclE9PQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: bitwarden-access-token
  namespace: external-secrets
