apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-crds-helm
  namespace: argocd
spec:
  destination:
    namespace: kgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kgateway-crds
    helm:
      skipCrds: false
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    targetRevision: v2.0.4
  syncPolicy:
    automated:
      # Prune resources during auto-syncing (default is false)
      prune: true 
      # Sync the app in part when resources are changed only in the target Kubernetes cluster
      # but not in the git source (default is false).
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true 

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-helm
  namespace: argocd
spec:
  destination:
    namespace: kgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kgateway
    helm:
      skipCrds: false
      parameters:
      - name: controller.image.pullPolicy
        value: "Always"
      values: |
        agentGateway:
          enabled: true
        gateway:
          aiExtension:
            enabled: true
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    targetRevision: v2.0.4
  syncPolicy:
    automated:
      # Prune resources during auto-syncing (default is false)
      prune: true 
      # Sync the app in part when resources are changed only in the target Kubernetes cluster
      # but not in the git source (default is false).
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
  