apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-local
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kagent-local
  sources:
    - repoURL: https://github.com/HiddenTechVillage/k8s-dev.git
      path: charts/kagent-local
      targetRevision: HEAD
    - repoURL: ghcr.io/kagent-dev/kagent/helm
      chart: kagent-crds
      targetRevision: 0.3.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true