apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-github
  namespace: kagent
spec:
  description: GitHub MCP Server
  config:
    stdio:
      args:
      - -y
      - "@modelcontextprotocol/server-github"
      command: npx
