
## Server
Server:
  # -- Additional command line arguments to pass to repo server
  extraArgs:
  - --insecure

## Argo Configs
configs:
  # General Argo CD configuration. Any values you put under `.configs.cm` are passed to argocd-cm ConfigMap.
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  cm:
    create: true
    accounts.homepage: apiKey, login
    accounts.homepage.enabled: "true"

  rbac:
    policy.csv: |
      g, homepage, role:readonly
