{{- $dot := . }}
{{- $model := index $dot.Values.providers $dot.Values.providers.default  }}
{{- if $model.apiKeySecretRef }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $model.apiKeySecretRef | quote }}
  labels:
    {{- include "kagent.labels" $dot | nindent 4 }}
type: Opaque
data:
{{- end }}
