apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: toolservers.kagent.dev
spec:
  group: kagent.dev
  scope: Namespaced
  names:
    plural: toolservers
    singular: toolserver
    kind: ToolServer
    listKind: ToolServerList
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: ToolServer is the Schema for the toolservers API.
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - config
                - description
              properties:
                description:
                  type: string
                config:
                  type: object
                  properties:
                    sse:
                      type: object
                      required:
                        - url
                      properties:
                        url:
                          type: string
                        timeout:
                          type: string
                        sse_read_timeout:
                          type: string
                        headers:
                          x-kubernetes-preserve-unknown-fields: true
                    stdio:
                      type: object
                      required:
                        - command
                      properties:
                        command:
                          type: string
                        args:
                          type: array
                          items:
                            type: string
                        env:
                          type: array
                          items:
                            type: object
                            required:
                              - name
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                              valueFrom:
                                type: object
                                properties:
                                  secretKeyRef:
                                    type: object
                                    required:
                                      - name
                                      - key
                                    properties:
                                      name:
                                        type: string
                                      key:
                                        type: string
            status:
              type: object
              description: ToolServerStatus defines the observed state of ToolServer.
              required:
                - conditions
                - observedGeneration
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                        maxLength: 32768
                      reason:
                        type: string
                        minLength: 1
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      type:
                        type: string
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                observedGeneration:
                  type: integer
                  format: int64
                discoveredTools:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - component
                    properties:
                      name:
                        type: string
                      component:
                        type: object
                        required:
                          - component_type
                          - component_version
                          - description
                          - label
                          - provider
                          - version
                        properties:
                          component_type:
                            type: string
                          component_version:
                            type: integer
                          config:
                            x-kubernetes-preserve-unknown-fields: true
                          description:
                            type: string
                          label:
                            type: string
                          provider:
                            type: string
                          version:
                            type: integer
      subresources:
        status: {}
