apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.22.0
    helm:
      vaules: |
          dns:
            enabled: true
            type: NodePort
            port: 53

          adminPassword: "changeme"

          serviceWeb:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.53

          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
            hosts:
              - host: pihole.chris
                paths:
                  - path: /
                    pathType: Prefix

          persistentVolumeClaim:
            enabled: true
            storageClass: ""
            accessModes:
              - ReadWriteOnce
            size: 500Mi

          extraEnvVars:
            TZ: America/Edmonton


  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
