apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-notion
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: notion-api-token
    remoteRef:
      key: "30d3d7cc-836c-475d-adca-b2ca00fe5437"
