apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-notion
  namespace: kagent
spec:
  description: Notion MCP Server
  config:
    stdio:
      command: npx
      args:
        - -y
        - "@notionhq/notion-mcp-server"
      env:
        OPENAPI_MCP_HEADERS: '{\"Authorization\":\"Bearer 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\",\"Notion-Version\":\"2022-06-28\"}'
