apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-notion
  namespace: kagent
spec:
  description: notion MCP Server
  config:
    stdio:
      args:
      - -y
      - "@notionhq/notion-mcp-server"
      command: npx
      env:
        OPENAPI_MCP_HEADERS: "{\"Authorization\": \"Bearer ntn_****\", \"Notion-Version\": \"2022-06-28\" }"