apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-notion
  namespace: kagent
spec:
  description: Notion MCP Server
  config:
    stdio:
      command: npx
      args:
        - -y
        - "@notionhq/notion-mcp-server"
