apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent    
  sources:
    - repoURL: ghcr.io/kagent-dev/kagent/helm
      chart: kagent-crds
      targetRevision: 0.6.0
      helm:
        releaseName: kagent-crds
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-mcp-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kmcp-system
  sources:
    - repoURL: ghcr.io/kagent-dev/kmcp/helm
      chart: kagent-crds
      targetRevision: 0.6.0
      helm:
        releaseName: kagent-crds
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
