apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  commonName: bitwarden-sdk-server.external-secrets.svc.cluster.chris
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.chris
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
