apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  commonName: bitwarden-sdk-server.external-secrets.svc.cluster.dev
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.dev
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
