apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.15.1
    helm:
      releaseName: external-secrets
      values: |
        bitwarden-sdk-server:
          enabled: true
          image:
            repository: ghcr.io/external-secrets/bitwarden-sdk-server
            pullPolicy: IfNotPresent
            tag: ""  # Defaults to chart appVersion
            tls:
              enabled: true
              certManager:
                enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
