{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bitwarden-access-token",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bitwarden-access-token",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "key": "AgCqgJq9lS/m1412sIbNGXLywzUCyByxqSZWfh1oj3UeT/GRewZ5CErKL+oaWNyQaDz9WRTzUP/xSUansXxtWPtuwMsRmuDCEgOeENRi3IxHhcMNZnjkgh6sP94hasZ+iW6VBYsu2BmvSMep6TWCYw3TWva7xiwEx7Tl/V1GTLCg5kQW2tdggwMWXxjHqOWbRLP3wPl38tE0qiQq+03bsW7n4wZWDN7Tbd8izyQWKQ59PhOCTLoOGYGjLqTuyQ0tJy6nFQgV32kZ1Ia5iXg2CUUefYXOBbJpNWFq1P4X1BP7gQWZ9MrAI8n9OQYGD+cWcCkKX4Y8xtzAHHoSgdS5Fh5EX0iAHDcrD8zF1hezcexBsdeSRyzpnXNIforHZXsO0wqFNk5PuXsf4VfwEtorpttI59Qqrwhb5ZrRbTPOzEV+3c6ZhSeuOLghKprWOO7lGCJeH63kYm8rq7jRNe6X18oFKHNh7AK2XBNsUmDMpEcuYWLxuNHuYsqdRZQnUsA04tmdvYbiHd6HGhnok/dEqJX4HnkEophNzpR7nN/5uBfakxAPpWiqCMSb75KFEOEgsvpz5GZj4cZjuF4Xi4KvSYodjNitbLnuR0K2ILEpuW+h+akc3oLhjjM66KA/juqq5RvakoJVqc8wtvm1/N3JQU1/euyTo7NRS63rLznE4xicA1IeWuSJps14mBi82u95u/jEmgYhp3OhoUQ1cinR3344geacxW7ftk5ULak/T6dFWBVRmTBwlLx1wTKdfbgiz90qt6glzgsj6pJiqlArV/rLp3zLj4lhuzEqZtQ/IzDFU/kDIEMbzXke7BkJgzPm"
    }
  }
}
