apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 1.20.0
  destination:
      server: https://kubernetes.default.svc
      namespace: crossplane-system
  syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        selfHeal: true
        prune: true
