apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kagent-tls-certs
  namespace: kagent
spec:
  secretName: kagent-tls-certs
  dnsNames:
    - kagent.chris
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
