
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
        - Personal Blog:
            - abbr: BG
              href: https://chrismatcham.dev/
  services.yaml: |
    - CI / CD:
        - ArgoCD:
            href: https://argocd.local:30443/
            description: GitOps CD
            widget:
              type: argocd
              url: https://argocd-server.argocd.svc.cluster.local:443/
              key: "{{ .argocd-homepage | toString }}"

    - Apps:
        - Test Application:
            href: https://testapp.local:30443/
            description: Super Basic App

    - Monitoring:
        - Grafana:
            href: hhttps://grafana.local:30443/
            description: Super Simple K8s Dashboard
            widget:
              type: grafana
              url: https://kube-prometheus-stack-operator.monitoring.svc.cluster.local:443
              username: username
              password: password
        - Kubernetes Dashboard:
            href: https://kubernetes-dashboard.local:30443/
            description: Super Simple K8s Dashboard
        - Uptime Kuma:
            href: https://uptime-kuma.local:30443/
            description: Super Simple Uptime Monitoring
            widget:
              type: uptimekuma
              url: https://uptime-kuma.monitoring.svc.cluster.local:3001
              slug: k8s-dev

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - openweathermap:
        label: Calgary #optional
        latitude: 51.049999
        longitude: -114.066666
        units: metric # or imperial
        provider: openweathermap
        apiKey: "{{ .key | toString }}"
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 1
  docker.yaml: ""