# ExternalSecret (final services.yaml rendered with real secret)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-services
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: homepage-services
    template:
      templateFrom:
      - configMap:
          name: homepage
          items:
          - key: services.yaml
  data:
  - secretKey: argocd-homepage
    remoteRef:
      key: "30d3d7cc-836c-475d-adca-b2ca00fe5437"


---

# ExternalSecret (final services.yaml rendered with real secret)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-widgets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: homepage-widgets
    template:
      templateFrom:
      - configMap:
          name: homepage
          items:
          - key: widgets.yaml
  data:
  - secretKey: key
    remoteRef:
      key: "9c4784e4-9d9a-4a12-aa03-b2ca00ef3087"
