apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weather-api-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: weather-api-key
    remoteRef:
      key: "9c4784e4-9d9a-4a12-aa03-b2ca00ef3087"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-homepage-api-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: argocd-homepage-api-key
    template:
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: homepage
          # here you define the keys that should be used as template
          items:
          - key: services.yaml
  data:
  - secretKey: user
    remoteRef:
      key: /grafana/user
  - secretKey: key
    remoteRef:
      key: "30d3d7cc-836c-475d-adca-b2ca00fe5437"
