# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: metal-lb
#   namespace: argocd
# spec:
#   project: default
#   sources:
#       - repoURL: https://github.com/HiddenTechVillage/k8s-dev.git
#         targetRevision: HEAD
#         path: argocd/applications/metal-lb
#         directory:
#           recurse: true
#   destination:
#       server: https://kubernetes.default.svc
#       namespace: metallb-system
#   syncPolicy:
#       syncOptions:
#       - CreateNamespace=true
#       automated:
#         selfHeal: true
#         prune: true
