apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-atlassian
  namespace: kagent
spec:
  description: Atlassian MCP Server for Jira and Confluence
  config:
    stdio:
      args:
        - mcp-atlassian@latest
        - stdio
      command: npx
      env:
        JIRA_URL: "https://chrismatcham.atlassian.net"
        CONFLUENCE_URL: "https://chrismatcham.atlassian.net/wiki"
      # argsFrom:
      #   - name: JIRA_API_TOKEN
      #     valueFrom:
      #       secretKeyRef:
      #         name: mcp-atlassian
      #         key: jira-api-token
      #         prefix: --JIRA_API_TOKEN=
      #   - name: CONFLUENCE_API_TOKEN
      #     valueFrom:
      #       secretKeyRef:
      #         name: mcp-atlassian
      #         key: confluence-api-token
      #         prefix: --CONFLUENCE_API_TOKEN=