apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-atlassian
  namespace: kagent        
spec:
  description: ArgoCD MCP Server
  config:
    stdio:
      args:
      - phuc-nt/mcp-atlassian-server@2.1.1
      - stdio
      command: npx
      env:
        test: test
      # - name: CONFLUENCE_URL
      #   value: "https://chrismatcham.atlassian.net/wiki"
      # - name: JIRA_URL
      #   value: "https://chrismatcham.atlassian.net"
      # - name: CONFLUENCE_API_TOKEN
      #   valueFrom:
      #     secretKeyRef:
      #       name: mcp-atlassian
      #       key: confluence-api-token
      # - name: JIRA_API_TOKEN
      #   valueFrom:
      #     secretKeyRef:
      #       name: mcp-atlassian
      #       key: jira-api-token