apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-application-tls
  namespace: default
spec:
  secretName: test-application-tls
  dnsNames:
    - testapp.localdev
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
