apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
spec:
  project: default
  source:
      repoURL: https://github.com/HiddenTechVillage/k8s-dev.git
      targetRevision: HEAD
      path: cluster-services/kagent
  destination:
      server: https://kubernetes.default.svc
      namespace: kagent
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
