apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql 
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.6.3
    helm:
      releaseName: postgresql
      values: |
        auth:
          username: myuser
          password: mypassword
          database: mydb
        primary:
          persistence:
            enabled: true
            size: 8Gi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
