apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql 
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: latest
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true