apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: yt-agent
  namespace: default
spec:
  type: Declarative
  declarative:
    modelConfig: default-model-config
    systemMessage: "When given a YouTube URL/ID, c