# toolserver-yt.yaml
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: yt-kmcp
  namespace: default
spec:
  config:
    streamableHttp:
      sseReadTimeout: 5m0s
      timeout: 30s
      url: http://yt-kmcp-kagent.default.svc:3000/mcp
    type: streamableHttp
  description: test server

---

# agent-yt.yaml
apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: yt-agent
  namespace: default
spec:
  description: Agent that calls the YouTube MCP tool.
  modelConfig: default-model-config
  systemMessage: |-
    When given a YouTube URL or ID, call the "get_video_info" tool.
    Summarize clearly.
  tools:
  - mcpServer:
      toolNames:
      - get_video_info
      toolServer: yt-kmcp
    type: McpServer
