apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: yt-agent
  namespace: default
spec:
  description: Agent that calls the YouTube MCP tool to fetch title/description/transcript.
  modelConfig: default-model-config
  systemMessage: |-
    You are a pragmatic cloud engineer agent. When given a YouTube URL or ID,
    call the "get_video_info" MCP tool to return title, description, and transcript (if available).
    Summarize clearly.
  tools:
    - type: McpServer
      mcpServer:
        kind: Service
        name: yt-kmcp-kagent
        toolNames:
          - get_video_info
