# toolserver-yt.yaml
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: yt-kmcp
  namespace: default
spec:
  description: YouTube MCP (Streamable HTTP via agent-gateway)
  config:
    type: streamableHttp
    streamableHttp:
      url: http://yt-kmcp-kagent.default.svc:3000/mcp
      # optional timeouts/headers:
      # timeout: 30s
      # sseReadTimeout: 30s
---

# agent-yt.yaml
apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: yt-agent
  namespace: default
spec:
  description: Agent that calls the YouTube MCP tool.
  modelConfig: default-model-config
  systemMessage: |-
    When given a YouTube URL or ID, call the "get_video_info" tool.
    Summarize clearly.
