apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.1
    helm:
      releaseName: cert-manager
      values: |
        crds:
        # This option decides if the CRDs should be installed
        # as part of the Helm installation.
          enabled: false

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
