apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: cert-manager
type: kubernetes.io/tls
data:
  # values are base64 encoded, which obscures them but does NOT provide
  # any useful level of confidentiality
  tls.crt: |
    dGVzdAo=
  # In this example, the key data is not a real PEM-encoded private key
  tls.key: |
    dGVzdAo=