apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.53/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-adv
  namespace: metallb-system
