  apiVersion: kagent.dev/v1alpha1
  kind: ToolServer
  metadata:
    name: terraform-mcp-gitops
    namespace: kagent
  spec:
    description: ArgoCD MCP Server
    config:
      stdio:
        args:
        - run
        - -i
        - --rm
        - hashicorp/terraform-mcp-server:0.1.0
        command: docker
        env:
          ARGOCD_BASE_URL: "https://argocd-server.argocd.svc.cluster.local"
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
          # not ideal method to pass token
          ARGOCD_API_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhcmdvY2QtbWNwOmFwaUtleSIsIm5iZiI6MTc0Njc5ODkxNSwiaWF0IjoxNzQ2Nzk4OTE1LCJqdGkiOiI4OTU2MWY4My0xZmI5LTRlZmMtOTMyNS05MzkzMTRlMmE1MGUifQ.hiQls7T9Ie4VeD7uzQLuCA7p_h1IuClhX5Z3LrtJVHo"
        # argsFrom:
        # - name: ARGOCD_API_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: mcp-argocd
        #       key: argocd-api-token