  apiVersion: kagent.dev/v1alpha1
  kind: ToolServer
  metadata:
    name: terraform-mcp-gitops
    namespace: kagent
  spec:
    description: ArgoCD MCP Server
    config:
      stdio:
        args:
        - run
        - -i
        - --rm
        - hashicorp/terraform-mcp-server:0.1.0
        command: docker
