apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kagent-local-tls-certs
  namespace: kagent-local
spec:
  secretName: kagent-local-tls-certs
  commonName: kagent.kagent.svc.cluster.local
  dnsNames:
    - kagent-local.kagent.svc.cluster.local
    - kagent-local.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
