apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-application
  template:
    metadata:
      labels:
        app: test-application
    spec:
      containers:
      - name: test-application
        image: matcham89/app:latest
        ports:
        - containerPort: 5000
        env:
        - name: APP_MESSAGE
          value: "Test Application"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: bitwarden
              key: test


