apiVersion: v1
kind: Service
metadata:
  name: test-application
spec:
  selector:
    app: test-application
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 5000
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000