apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-atlassian
  labels:
    app: mcp-atlassian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-atlassian
  template:
    metadata:
      labels:
        app: mcp-atlassian
    spec:
      containers:
      - name: mcp-atlassian
        image: ghcr.io/sooperset/mcp-atlassian:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONFLUENCE_URL
          value: "https://chrismatcham.atlassian.net/wiki"
        - name: JIRA_URL
          value: "https://chrismatcham.atlassian.net"
        - name: CONFLUENCE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-atlassian
              key: confluence-api-token
        - name: JIRA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-atlassian
              key: jira-api-token