apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-atlassian
  namespace: kagent  # Adjust to your namespace if different
spec:
  description: Fetches a website and returns its content
  config:
    stdio:
      args: ["stdio"]
      command: "npx mcp-atlassian@latest"
      # env:
      # - name: CONFLUENCE_URL
      #   value: "https://chrismatcham.atlassian.net/wiki"
      # - name: JIRA_URL
      #   value: "https://chrismatcham.atlassian.net"
      # - name: CONFLUENCE_API_TOKEN
      #   valueFrom:
      #     secretKeyRef:
      #       name: mcp-atlassian
      #       key: confluence-api-token
      # - name: JIRA_API_TOKEN
      #   valueFrom:
      #     secretKeyRef:
      #       name: mcp-atlassian
      #       key: jira-api-token