apiVersion: v1
kind: Service
metadata:
  name: mcp-atlassian
  namespace: kagent
spec:
  selector:
    app: mcp-atlassian
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080