apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-argocd-gitops
  namespace: kagent
spec:
  description: ArgoCD MCP Server
  config:
    stdio:
      args:
      - argocd-mcp@latest
      - stdio
      command: npx
      env:
        - name: ARGOCD_BASE_URL
          value: "https://argocd-server.argocd.svc.cluster.local"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: ARGOCD_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-argocd
              key: argocd-api-token
